/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ruli_RuliSyncImp */

#ifndef _Included_ruli_RuliSyncImp
#define _Included_ruli_RuliSyncImp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ruli_RuliSyncImp
 * Method:    srvQuery
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_ruli_RuliSyncImp_srvQuery
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

/*
 * Class:     ruli_RuliSyncImp
 * Method:    smtpQuery
 * Signature: (Ljava/lang/String;I)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_ruli_RuliSyncImp_smtpQuery
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ruli_RuliSyncImp
 * Method:    httpQuery
 * Signature: (Ljava/lang/String;II)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_ruli_RuliSyncImp_httpQuery
  (JNIEnv *, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
